In [ ]:
print('hello')

hello


In [1]:
!pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 KB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp39-cp39-linux_x86_64.whl size=3193609 sha256=5e60c46c8c9d72b2c5191939e1d49d8987e19f6c6b8f01d14ac44fb430c52ee9
  Stored in directory: /root/.cache/pip/wheels/c6/3a/46/9b17b3512bdf283c6cb84f59929cdd5199d4e754d596d22784
Successfully built scikit-surprise


In [2]:
import numpy as np
import pandas as pd 
import math # 불러오기 수학과 관련된 함수
import re # 정규표현식 함수 , 판별 여부
from scipy.sparse import csr_matrix # 매트릭스 해줌
import matplotlib.pyplot as plt # 시각화 함수
import seaborn as sns # 시각화 함수
import json
import mpmath
from scipy.special import logsumexp

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/ml_plus/data')

In [44]:
df =  pd.read_csv('영화 & TV 데이터.csv', index_col= 0, encoding='CP949')

In [8]:
df

contentId                                  title  \
0         943822  Prizefighter: The Life of Jem Belcher   
1         315162                      장화신은 고양이: 끝내주는 모험   
2         505642                         블랙 팬서: 와칸다 포에버   
3         631842                                    똑똑똑   
4        1011679                 Shark Side of the Moon   
...          ...                                    ...   
20053      71209                                그레이트 뉴스   
20054     203805                          드래곤 에이지: 앱솔루션   
20055     120932         Expedition: Back to the Future   
20057      95380                               영검산의 고수들   
20058     114497                         종극필기: 최후의 어드벤처   

                            genre  \
0                     '드라마', '역사'   
1      '애니메이션', '모험', '코미디', '가족'   
2                '액션', '모험', 'SF'   
3             '공포', '미스터리', '스릴러'   
4         '액션', 'SF', '스릴러', '공포'   
...                           ...   
20053                       '코미디'   
20054  '애니메이션', '액션&모험', 'SF&판타지'   
20055              '코미디', '다큐멘터리'   
20057    '액션&모험', '코미디', 'SF&판타지'   
20058               '드라마', '미스터리'   

                                                 content  \
0                                                    NaN   
1      아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이. 마지막 남은 목숨을 지...   
2      국왕이자 블랙 팬서인 티찰라의 죽음 이후 수많은 강대국으로부터 위협을 받게 된 와칸...   
3      휴가를 떠난 한 가족은 별장에 무단침입한 낯선 방문자들과 대치하게 된다. ‘레너드’...   
4                                                    NaN   
...                                                  ...   
20053  야심만만한 TV 뉴스 프로듀서 케이티. 성공을 향해 앞만 보고 달려도 모자랄 판에 ...   
20054  메이지와 도적으로 구성된 반란군이 위험한 유물을 가진 사악한 힘에 정면으로 맞선다....   
20055                                                NaN   
20057  때는 바야흐로 4233년 아홉 대륙과 다섯 문파가 존재하는 곳. 수천 년에 한 번 ...   
20058  알 수 없는 내용의 비디오테이프를 받은 사람들 '최후'의 비밀을 파헤치기 위해 기나...   

                                                  imgUrl  contentRating  \
0      https://image.tmdb.org/t/p/w342/x3PIk93PTbxT88...            7.2   
1      https://image.tmdb.org/t/p/w342/rKgvctIuPXyuqO...            8.4   
2      https://image.tmdb.org/t/p/w342/3PCRWLeqp5y20k...            7.3   
3      https://image.tmdb.org/t/p/w342/mCDSOfcVJfMkGU...            6.4   
4      https://image.tmdb.org/t/p/w342/v5CfpzxoJDkZxj...            5.4   
...                                                  ...            ...   
20053  https://image.tmdb.org/t/p/w342/vEqPNbSY0mJmly...            6.5   
20054  https://image.tmdb.org/t/p/w342/aClwKQ6VIwlMaZ...            6.7   
20055  https://image.tmdb.org/t/p/w342/5b0XqGhFxLYUXw...            7.0   
20057  https://image.tmdb.org/t/p/w342/ndE8uy11sVH8KA...            5.5   
20058  https://image.tmdb.org/t/p/w342/ixVB81tIqPShkl...            8.4   

      createdYear  ratingCount   type  
0      2022-06-30           57  movie  
1      2022-12-07         4715  movie  
2      2022-11-09         4193  movie  
3      2023-02-01         1055  movie  
4      2022-08-12           94  movie  
...           ...          ...    ...  
20053  2017-04-25           56     tv  
20054  2022-12-09           47     tv  
20055  2021-03-15           98     tv  
20057  2019-11-12           11     tv  
20058  2020-12-10            7     tv  

[19466 rows x 9 columns]

In [46]:
df[df['ratingCount']> 100].index

Int64Index([    1,     2,     3,     6,     7,     8,     9,    10,    11,
               14,
            ...
            19832, 19849, 19871, 19883, 19901, 19910, 19991, 19995, 20006,
            20014],
           dtype='int64', length=10358)

In [54]:
df.drop(index = df[df['ratingCount'] < 100].index, inplace=True )

In [55]:
df

contentId                            title                       genre  \
1         315162                장화신은 고양이: 끝내주는 모험  '애니메이션', '모험', '코미디', '가족'   
2         505642                   블랙 팬서: 와칸다 포에버            '액션', '모험', 'SF'   
3         631842                              똑똑똑         '공포', '미스터리', '스릴러'   
6         785084                             더 웨일                       '드라마'   
7         646389                              플레인           '액션', '모험', '스릴러'   
...          ...                              ...                         ...   
19910     104108                           리얼리티 Z                    'SF&판타지'   
19991      26101                          천사들의 증언       '다큐멘터리', '미스터리', '범죄'   
19995      99385                          멈출 수 없어                       '드라마'   
20006     115970                          50 제곱미터                '범죄', '미스터리'   
20014      58565  Amy, la nina de la mochila azul                 '가족', '어린이'   

                                                 content  \
1      아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이. 마지막 남은 목숨을 지...   
2      국왕이자 블랙 팬서인 티찰라의 죽음 이후 수많은 강대국으로부터 위협을 받게 된 와칸...   
3      휴가를 떠난 한 가족은 별장에 무단침입한 낯선 방문자들과 대치하게 된다. ‘레너드’...   
6      272kg의 거구로 세상을 거부한 채 살아가는 대학 강사 찰리는 남은 시간이 얼마 ...   
7      평소와 다를 것 없던 어느 날 기장 토렌스는 비행기 운행 중 거대한 폭풍우를 만나 ...   
...                                                  ...   
19910  피가 튀고 살점이 뜯기는 생지옥에 남겨진 TV쇼 참가자들. 밖은 이미 좀비들의 세상...   
19991  1969년 벌어진 캐시 세스닉 수녀 살인 사건을 다룬 다큐멘터리 시리즈. 생존자들의...   
19995  강압적인 부모 직장에서의 갈등 불투명한 진로. 남 부러울 것 없는 20대 그녀들에게...   
20006  악랄한 보스를 배신한 후 도망자 신세가 된 청부살인업자. 빈 양복점에서 정신을 차린...   
20014                                                NaN   

                                                  imgUrl  contentRating  \
1      https://image.tmdb.org/t/p/w342/rKgvctIuPXyuqO...            8.4   
2      https://image.tmdb.org/t/p/w342/3PCRWLeqp5y20k...            7.3   
3      https://image.tmdb.org/t/p/w342/mCDSOfcVJfMkGU...            6.4   
6      https://image.tmdb.org/t/p/w342/q0xV5Lnq30Jieg...            8.1   
7      https://image.tmdb.org/t/p/w342/8XDLgSlM6hb01i...            6.9   
...                                                  ...            ...   
19910  https://image.tmdb.org/t/p/w342/hpqLI8lq8u1biq...            6.8   
19991  https://image.tmdb.org/t/p/w342/7xwOmCNOTcb5GU...            7.5   
19995  https://image.tmdb.org/t/p/w342/1hHQntkBMaV88U...            8.5   
20006  https://image.tmdb.org/t/p/w342/3m0aiNtGZo6URf...            7.4   
20014  https://image.tmdb.org/t/p/w342/7jzXcFyrqTLGDz...            7.2   

      createdYear  ratingCount   type  
1      2022-12-07         4715  movie  
2      2022-11-09         4193  movie  
3      2023-02-01         1055  movie  
6      2022-12-09         1478  movie  
7      2023-01-12          920  movie  
...           ...          ...    ...  
19910  2020-06-10          236     tv  
19991  2017-05-19          132     tv  
19995  2020-02-28          150     tv  
20006  2021-01-27          109     tv  
20014  2004-02-23          146     tv  

[10391 rows x 9 columns]

In [56]:
x = df.drop(['content','imgUrl','createdYear','type'],axis=1)

In [57]:
x

contentId                            title                       genre  \
1         315162                장화신은 고양이: 끝내주는 모험  '애니메이션', '모험', '코미디', '가족'   
2         505642                   블랙 팬서: 와칸다 포에버            '액션', '모험', 'SF'   
3         631842                              똑똑똑         '공포', '미스터리', '스릴러'   
6         785084                             더 웨일                       '드라마'   
7         646389                              플레인           '액션', '모험', '스릴러'   
...          ...                              ...                         ...   
19910     104108                           리얼리티 Z                    'SF&판타지'   
19991      26101                          천사들의 증언       '다큐멘터리', '미스터리', '범죄'   
19995      99385                          멈출 수 없어                       '드라마'   
20006     115970                          50 제곱미터                '범죄', '미스터리'   
20014      58565  Amy, la nina de la mochila azul                 '가족', '어린이'   

       contentRating  ratingCount  
1                8.4         4715  
2                7.3         4193  
3                6.4         1055  
6                8.1         1478  
7                6.9          920  
...              ...          ...  
19910            6.8          236  
19991            7.5          132  
19995            8.5          150  
20006            7.4          109  
20014            7.2          146  

[10391 rows x 5 columns]

In [58]:
x['genre'] = x['genre'].str.replace("&","")

In [59]:
x['genre'] = x['genre'].str.replace("'","")

In [60]:
x['genre'] = x['genre'].str.replace(",","")

In [61]:
x

contentId                            title            genre  \
1         315162                장화신은 고양이: 끝내주는 모험  애니메이션 모험 코미디 가족   
2         505642                   블랙 팬서: 와칸다 포에버         액션 모험 SF   
3         631842                              똑똑똑      공포 미스터리 스릴러   
6         785084                             더 웨일              드라마   
7         646389                              플레인        액션 모험 스릴러   
...          ...                              ...              ...   
19910     104108                           리얼리티 Z            SF판타지   
19991      26101                          천사들의 증언    다큐멘터리 미스터리 범죄   
19995      99385                          멈출 수 없어              드라마   
20006     115970                          50 제곱미터          범죄 미스터리   
20014      58565  Amy, la nina de la mochila azul           가족 어린이   

       contentRating  ratingCount  
1                8.4         4715  
2                7.3         4193  
3                6.4         1055  
6                8.1         1478  
7                6.9          920  
...              ...          ...  
19910            6.8          236  
19991            7.5          132  
19995            8.5          150  
20006            7.4          109  
20014            7.2          146  

[10391 rows x 5 columns]

In [67]:
x = x.dropna(axis=0)

In [68]:
x

contentId                            title            genre  \
0         315162                장화신은 고양이: 끝내주는 모험  애니메이션 모험 코미디 가족   
1         505642                   블랙 팬서: 와칸다 포에버         액션 모험 SF   
2         631842                              똑똑똑      공포 미스터리 스릴러   
3         785084                             더 웨일              드라마   
4         646389                              플레인        액션 모험 스릴러   
...          ...                              ...              ...   
10377     104108                           리얼리티 Z            SF판타지   
10378      26101                          천사들의 증언    다큐멘터리 미스터리 범죄   
10379      99385                          멈출 수 없어              드라마   
10380     115970                          50 제곱미터          범죄 미스터리   
10381      58565  Amy, la nina de la mochila azul           가족 어린이   

       contentRating  ratingCount  
0                8.4         4715  
1                7.3         4193  
2                6.4         1055  
3                8.1         1478  
4                6.9          920  
...              ...          ...  
10377            6.8          236  
10378            7.5          132  
10379            8.5          150  
10380            7.4          109  
10381            7.2          146  

[10382 rows x 5 columns]

In [69]:
x = x.reset_index()

In [70]:
x = x.drop('index',axis=1)

In [71]:
x = x.drop_duplicates(['title']).reset_index().drop('index',axis=1)

In [72]:
x

contentId                            title            genre  \
0         315162                장화신은 고양이: 끝내주는 모험  애니메이션 모험 코미디 가족   
1         505642                   블랙 팬서: 와칸다 포에버         액션 모험 SF   
2         631842                              똑똑똑      공포 미스터리 스릴러   
3         785084                             더 웨일              드라마   
4         646389                              플레인        액션 모험 스릴러   
...          ...                              ...              ...   
10011     104108                           리얼리티 Z            SF판타지   
10012      26101                          천사들의 증언    다큐멘터리 미스터리 범죄   
10013      99385                          멈출 수 없어              드라마   
10014     115970                          50 제곱미터          범죄 미스터리   
10015      58565  Amy, la nina de la mochila azul           가족 어린이   

       contentRating  ratingCount  
0                8.4         4715  
1                7.3         4193  
2                6.4         1055  
3                8.1         1478  
4                6.9          920  
...              ...          ...  
10011            6.8          236  
10012            7.5          132  
10013            8.5          150  
10014            7.4          109  
10015            7.2          146  

[10016 rows x 5 columns]

In [73]:
# 장르 백터화 
from sklearn.feature_extraction.text import CountVectorizer

In [74]:
counter_vector = CountVectorizer(ngram_range=(1,3))

In [75]:
c_vector_genre = counter_vector.fit_transform(x['genre'])

In [76]:
c_vector_genre.shape

(10016, 1915)

In [77]:
c_vector_genre

<10016x1915 sparse matrix of type '<class 'numpy.int64'>'
	with 50361 stored elements in Compressed Sparse Row format>

In [78]:
# 유사도 값 추출 ( 코사인 유사도 )
from sklearn.metrics.pairwise import cosine_similarity

similarity_genre = cosine_similarity(c_vector_genre, c_vector_genre).argsort()[:,::-1]
print(similarity_genre)

[[    0  2988  2265 ...  4384  4385  5007]
 [ 5253   920  2117 ...  6793  6797  5007]
 [ 3143  2546  1425 ...  6422  6423     0]
 ...
 [ 2838  4698  2958 ...  5287  5289     0]
 [10014  8296  3837 ...  6235  6236     0]
 [10015  8228  8273 ...  5937  5938  5007]]


In [79]:
similarity_genre.shape

(10016, 10016)

In [80]:
def recommend_movie_list(x, title, top= 30):
# 특정 영화 정보 뽑아내기
  target_movie_index = x[x['title'] == title].index.values
# 타겟 영화와 비슷한 코사인 유사도 값
  sim_index = similarity_genre[target_movie_index, :top].reshape(-1)
# 본인 제외
  sim_index = sim_index[sim_index!=target_movie_index]
# 추천 결과 새로운 df 생성 , 컨텐츠 레이팅으로 정렬
  result = x.iloc[sim_index].sort_values('contentRating',ascending=False)[:10]

  return result

In [82]:
recommend_movie_list(x, title = '장화신은 고양이: 끝내주는 모험')

contentId                            title                genre  \
1835     501929                     미첼 가족과 기계 전쟁         애니메이션 모험 코미디   
39       573171              Huevitos Congelados      애니메이션 모험 코미디 가족   
106      676701             테드: 잃어버린 탐험가와 미라의 저주  애니메이션 모험 코미디 가족 판타지   
2450     277834                              모아나      모험 코미디 가족 애니메이션   
5249     587562                노아의 방주 2: 새로운 세계로      애니메이션 모험 코미디 가족   
1101       9340                              구니스            모험 코미디 가족   
818      778855               치킨래빗: 잃어버린 보물을 찾아서  애니메이션 모험 코미디 가족 판타지   
842      228326                       마놀로와 마법의 책  애니메이션 모험 코미디 가족 판타지   
1857     346648                            패딩턴 2            모험 코미디 가족   
3181      15601  Scooby-Doo! and the Cyber Chase         애니메이션 모험 코미디   

      contentRating  ratingCount  
1835            8.0         2343  
39              7.9          251  
106             7.7          220  
2450            7.6        11057  
5249            7.6          138  
1101            7.5         5029  
818             7.5          218  
842             7.5         2341  
1857            7.5         1945  
3181            7.3          444

In [83]:
import joblib

In [84]:
joblib.dump(recommend_movie_list,'recommend_content.pkl')

['recommend_content.pkl']